### ISSUE TITLE
type error in zome call?

### ISSUE THREAD

**Issue by mhuesch** [sacredcapital/rep_interchange#1]
on the [`holonix`](https://github.com/mhuesch/scaffolding/tree/holonix) branch, I switched to using Holonix, and it seems to have taken us a bit further, if I'm not mistaken?

after rebuilding via `npm run build` in the project root, I now see this output for `npm test`:

```
[nix-shell:~/projects/scaffolding/test]$ npm test

> holo-dsl-scaffolding-test@0.0.1 test /home/mhueschen/projects/scaffolding/test
> WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=1 tape test_*.js | faucet

⨯ Basic DSL program compilation
  not ok 1 Test threw an exception. See output for details.
    ---
      operator: fail
      at: <anonymous> (/home/mhueschen/projects/scaffolding/test/node_modules/@holochain/tryorama/lib/middleware.js:77:19)
      stack: |-
        Error: Test threw an exception. See output for details.
            at Test.assert [as _assert] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:304:54)
            at Test.bound [as _assert] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:91:32)
            at Test.fail (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:398:10)
            at Test.bound [as fail] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:91:32)
            at /home/mhueschen/projects/scaffolding/test/node_modules/@holochain/tryorama/lib/middleware.js:77:19
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
    ...
  01:30:27 [tryorama] debug: Test failed: Basic DSL program compilation {
    type: 'error',
    data: {
      type: 'internal_error',
      data: 'Conductor returned an error while using a ConductorApi: EntryDefStoreError(DnaError(WasmError(Compile("Error while importing \\"env\\".\\"__import_data\\": incompatible import type. Expected Function(FunctionType { params: [I32], results: [] }) but received Function(FunctionType { params: [], results: [I64] })"))))'
    }
  }
  01:30:27 [tryorama] debug: Cleaning up test: Basic DSL program compilation
  01:30:27 [tryorama] debug: Calling Api._cleanup. description: Basic DSL program compilation
  01:30:27 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
  01:30:27 [tryorama: player c0] debug: Shutting down...
  01:30:27 [tryorama: tryorama conductor c0] debug: Killing...
  01:30:27 [tryorama] info: conductor 'c0' exited with code null
  01:30:27 [tryorama: player c0] debug: Shut down.
  FIXME: ignoring onLeave
  01:30:27 [tryorama] debug: Finished with test: Basic DSL program compilation

# tests 1
# pass  0
⨯ fail  1
npm ERR! Test failed.  See above for more details.
```

@pospi - does this look like we made a type error in the zome call?

**Comment by pospi** [comment]
Hmm, looks like they may have changed some things. Did you recompile the
hApp as well?

You may now be in for some serious Cargo cache issues- I would wipe it
completely first. Problem is the HDK we built against and the latest one
both have the same version number, so it'll match whatever it has access to.

Another fix would be to use a path dependency in your Cargo.toml and point
it to the exact local HDK crate you have inside the cloned Holochain repo.

**Comment by pospi** [comment]
Another possibility is a changed format in the entrydefs extern, in which
case I'd just comment that one out or take a look at Elemental Chat and use
the same function signature.

**Comment by mhuesch** [comment]
hmm thx.

I found a nice-looking `default.nix` for `syn` [here](https://github.com/holochain/syn/blob/main/default.nix) and decided to try that, in case it would minimize config issues.

I've pushed those changes to a new branch: [holonix-2](https://github.com/mhuesch/scaffolding/tree/holonix-2) and the commands now manifest a different error.

`npm run build` works, after my having to set `CARGO_HOME` to `~/.cargo`.

then we see:

```
vayu :: projects/scaffolding/test ‹holonix-2*› » npm test

> holo-dsl-scaffolding-test@0.0.1 test /home/mhueschen/projects/scaffolding/test
> WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=1 tape test_*.js | faucet

⨯ Basic DSL program compilation
  not ok 1 Test threw an exception. See output for details.
    ---
      operator: fail
      at: <anonymous> (/home/mhueschen/projects/scaffolding/test/node_modules/@holochain/tryorama/lib/middleware.js:77:19)
      stack: |-
        Error: Test threw an exception. See output for details.
            at Test.assert [as _assert] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:304:54)
            at Test.bound [as _assert] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:91:32)
            at Test.fail (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:398:10)
            at Test.bound [as fail] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:91:32)
            at /home/mhueschen/projects/scaffolding/test/node_modules/@holochain/tryorama/lib/middleware.js:77:19
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
    ...
  09:27:39 [tryorama] debug: Test failed: Basic DSL program compilation {
    type: 'error',
    data: {
      type: 'ribosome_error',
      data: 'Wasm error while working with Ribosome: Deserialize([192])'
    }
  }
  09:27:39 [tryorama] debug: Cleaning up test: Basic DSL program compilation
  09:27:39 [tryorama] debug: Calling Api._cleanup. description: Basic DSL program compilation
  09:27:39 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
  09:27:39 [tryorama: player c0] debug: Shutting down...
  09:27:39 [tryorama: tryorama conductor c0] debug: Killing...
  09:27:39 [tryorama] info: conductor 'c0' exited with code null
  09:27:39 [tryorama: player c0] debug: Shut down.
  FIXME: ignoring onLeave
  09:27:39 [tryorama] debug: Finished with test: Basic DSL program compilation

# tests 1
# pass  0
⨯ fail  1
npm ERR! Test failed.  See above for more details.
```

my guess is we are doing something subtly wrong with passing things across the WASM boundary? I think I'll look at `syn` and `elemental-chat` for clues.

**Comment by pospi** [comment]
Could be the test itself- still some serialisation quirks at the API boundary.

See line https://github.com/mhuesch/scaffolding/blob/main/test/test_scaffolding.js#L52  and try sending an empty object `const result = await scaffoldingApp.call('interpreter', 'test_output', {}) `

**Comment by mhuesch** [comment]
@pospi I now see 

```
vayu :: projects/scaffolding/test ‹holonix-2*› » npm test

> holo-dsl-scaffolding-test@0.0.1 test /home/mhueschen/projects/scaffolding/test
> WASM_LOG=debug RUST_LOG=error RUST_BACKTRACE=1 tape test_*.js | faucet

⨯ Basic DSL program compilation
  not ok 1 Test threw an exception. See output for details.
    ---
      operator: fail
      at: <anonymous> (/home/mhueschen/projects/scaffolding/test/node_modules/@holochain/tryorama/lib/middleware.js:77:19)
      stack: |-
        Error: Test threw an exception. See output for details.
            at Test.assert [as _assert] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:304:54)
            at Test.bound [as _assert] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:91:32)
            at Test.fail (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:398:10)
            at Test.bound [as fail] (/home/mhueschen/projects/scaffolding/test/node_modules/tape/lib/test.js:91:32)
            at /home/mhueschen/projects/scaffolding/test/node_modules/@holochain/tryorama/lib/middleware.js:77:19
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
    ...
  04:16:34 [tryorama] debug: Test failed: Basic DSL program compilation {
    type: 'error',
    data: {
      type: 'ribosome_error',
      data: 'Wasm error while working with Ribosome: Deserialize([128])'
    }
  }
  04:16:34 [tryorama] debug: Cleaning up test: Basic DSL program compilation
  04:16:34 [tryorama] debug: Calling Api._cleanup. description: Basic DSL program compilation
  04:16:34 [tryorama: player c0] debug: calling Player.cleanup, conductor: %b
  04:16:34 [tryorama: player c0] debug: Shutting down...
  04:16:34 [tryorama: tryorama conductor c0] debug: Killing...
  04:16:34 [tryorama] info: conductor 'c0' exited with code null
  04:16:34 [tryorama: player c0] debug: Shut down.
  FIXME: ignoring onLeave
  04:16:34 [tryorama] debug: Finished with test: Basic DSL program compilation

# tests 1
# pass  0
⨯ fail  1
npm ERR! Test failed.  See above for more details.
```

where diff tells me that the only difference (besides timestamps) is error code 128 vs 192. do you know if those codes are meaningful?

**Comment by mhuesch** [comment]
@pospi if you are up for it and have free space on your machine, cloning branch `holonix-2` and running `nix-shell` should (I hope?) set you up with a deterministically identical environment.

**Comment by mhuesch** [comment]
would this section of syn seem relevant to you? I can't quite make sense of what is calling what...

https://github.com/holochain/syn/blob/21a87e87a34c0180ec7eb4c0e4f15ae936c79081/ui/src/syn.js#L27-L54

**Comment by pospi** [comment]
Oops sorry, catching up. Is this still blocking? I was pretty sure it was just a generic deserialisation error to do with sending the wrong parameters to the method call from the JS layer. Or did you investigate that and come up empty?

FWIW I am *reasonably* sure that the deserialisation errors are just the bytes of what it's trying to deserialise. They're not very helpful :S

**Comment by mhuesch** [comment]
I think this can be closed, since we have a minimal end to end test running. thanks @pospi 🙂
